### PR TITLE
Fix tokenizer on and and or with no spaces around

### PR DESCRIPTION
**Pull request by denis-sokolov**

### CODE REVIEW

**Comment by boutell** [comment]
Whoops this isn't my repo. (: Thought you were on our doctrine1.

**Comment by denis-sokolov** [comment]
> I believe spaces are required elsewhere in DQL

Interesting. I can't find anywhere that this is true.
In fact, the documentation seems to show that [they are not](http://doctrine1.readthedocs.org/en/latest/en/manual/dql-doctrine-query-language.html#grammar-token-conditional_expression).
Do you have a citation that they are?

Even if they were, do you not agree that users (API users, that is, the developers)
expect to split the terms of a complex conditional into multiple lines?
Then many good editors and tools trim trailing spaces on lines
resulting in the broken behavior displayed by the test `"...) OR\n(..."` in this pull request.

**Comment by boutell** [comment]
Converting newlines to spaces would be a lot less likely to result in a
catch-22 for a developer who has added a DQL keyword that happens to begin
with the letters AND or OR.

On Mon, Aug 17, 2015 at 9:14 AM, Denis Sokolov notifications@github.com
wrote:

> I believe spaces are required elsewhere in DQL
> 
> Interesting. I can't find anywhere that this is true.
> In fact, the documentation seems to show that they are not
> http://doctrine1.readthedocs.org/en/latest/en/manual/dql-doctrine-query-language.html#grammar-token-conditional_expression
> .
> Do you have a citation that they are?
> 
> Even if they were, do you not agree that users (API users, that is, the
> developers)
> expect to split the terms of a complex conditional into multiple lines?
> Then many good editors and tools trim trailing spaces on lines
> resulting in the broken behavior displayed by the test "...) OR\n(..." in
> this pull request.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zikula/doctrine1/pull/1#issuecomment-131814506.

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by denis-sokolov** [comment]
> Converting newlines to spaces

That will break string literals that include literal newlines as well as still not covering the case `)OR(`.

My pull request did not break a single test that has not been failing before it.
It's sad that the coverage is so poor.
Do you think you could write a test for a custom keyword? I did not even know about such a feature.
(To run tests you must be in the `tests/` directory and run `php run.php`)

**Comment by boutell** [comment]
I think perhaps we'd better let the owners of the repo have an opinion
before I ask you to jump through any hoops (:

On Mon, Aug 17, 2015 at 10:00 AM, Denis Sokolov notifications@github.com
wrote:

> Converting newlines to spaces
> 
> That will break string literals that include literal newlines as well as
> still not covering the case )OR(.
> 
> My pull request did not break a single test that has not been failing
> before it.
> It's sad that the coverage is so poor.
> Do you think you could write a test for a custom keyword? I did not even
> know about such a feature.
> (To run tests you must be in the tests/ directory and run php run.php)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zikula/doctrine1/pull/1#issuecomment-131827642.

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by craigh** [comment]
Frankly we (the repo owners) aren't so sure about much :wink: I was under the (apparently mistaken) impression that this was a mirror repo only. So I figured we weren't taking any PRs but that is obviously false. Drak used to maintain this fork but he is long gone :sad: so I am not 100% sure on how to proceed because I am unfamiliar with the code.

**Comment by boutell** [comment]
Interesting (:

We were hit by the same problem, and we forked here:

https://github.com/punkave/doctrine1

Where we're primarily interested - exclusively really - in landing
backwards compatible bug fixes and newer-version-of-PHP-compatibility fixes
in the dev-master branch. dev-dev (the branch that gets snazzy new
features) is dead as far as we're concerned. We do all our new work in
nodejs, after all.

On Mon, Aug 17, 2015 at 10:06 AM, Craig Heydenburg <notifications@github.com

> wrote:
> 
> Frankly we (the repo owners) aren't so sure about much [image: :wink:] I
> was under the (apparently mistaken) impression that this was a mirror repo
> only. So I figured we weren't taking any PRs but that is obviously false.
> Drak used to maintain this fork but he is long gone :sad: so I am not 100%
> sure on how to proceed because I am unfamiliar with the code.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zikula/doctrine1/pull/1#issuecomment-131829095.

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by denis-sokolov** [comment]
I have already worked to consolidate Doctrine 1 support once.
Drak's version is [the most popular central place](https://packagist.org/search/?q=doctrine1&orderBys%5B0%5D%5Bsort%5D=downloads&orderBys%5B0%5D%5Border%5D=desc) for Doctrine 1. (`doctrine/doctrine1` is just a mirror, and receives no updates).

I have been adding backwards-compatible fixes to doctrine 1 once in a blue moon.
I happen to be [the top contributor](https://github.com/zikula/doctrine1/graphs/contributors) as meaningless as that is with such a low number of activity.

The dev branch is not meant to add snazzy new features.
It is meant for important fixes, that are nevertheless backwards-incompatible.
There's only one at the moment, 30e7e0da96.
It seems that the current issue might be another, if @boutell is correct in that the proposed solution breaks DQL keywords.

@craigh, I do not know how and why you have been passed Drak's fork, but now that you have it, you have a little bit of responsibility to go with it. :) Namely, it would be great if you could accept contributions.
If you only wish to have the repository as a static mirror, perhaps you could give me write access and/or transfer the project to allow these feeble attempts at fixing the most drastic of problems.

**Comment by boutell** [comment]
I don't know for certain that it could break a DQL keyword or a
customization of DQL. Just seems possible if you remove the whitespace from
the parsing.

On Mon, Aug 17, 2015 at 10:48 AM, Denis Sokolov notifications@github.com
wrote:

> I have already worked to consolidate Doctrine 1 support once.
> Drak's version is the most popular central place
> https://packagist.org/search/?q=doctrine1&orderBys%5B0%5D%5Bsort%5D=downloads&orderBys%5B0%5D%5Border%5D=desc
> for Doctrine 1. (doctrine/doctrine1 is just a mirror, and receives no
> updates).
> 
> I have been adding backwards-compatible fixes to doctrine 1 once in a blue
> moon.
> I happen to be the top contributor
> https://github.com/zikula/doctrine1/graphs/contributors as meaningless
> as that is with such a low number of activity.
> 
> The dev branch is not meant to add snazzy new features.
> It is meant for important fixes, that are nevertheless
> backwards-incompatible.
> There's only one at the moment, 30e7e0d
> https://github.com/zikula/doctrine1/commit/30e7e0da96f20ec7d9a748d6fafc2b885dba25ce
> .
> It seems that the current issue might be another, if @boutell
> https://github.com/boutell is correct in that the proposed solution
> breaks DQL keywords.
> 
> @craigh https://github.com/craigh, I do not know how and why you have
> been passed Drak's fork, but now that you have it, you have a little bit of
> responsibility to go with it. :) Namely, it would be great if you could
> accept contributions.
> If you only wish to have the repository as a static mirror, perhaps you
> could give me write access and/or transfer the project to allow these
> feeble attempts at fixing the most drastic of problems.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zikula/doctrine1/pull/1#issuecomment-131848368.

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by craigh** [comment]
perhaps I am missing something, but I only see one branch (master) here in this repo.

@denis-sokolov - drak was the lead dev for the zikula project until about one year ago. Recently his entire github account was deleted and in order that our project maintained it's dependencies we recovered the source to this repo and pointed the packagist links here as well.

moving forward, I will discuss what we can do with our core dev team and get back to you. We have several options:
1. maintain the repo and merge PRs when deemed appropriate
2. maintain the repo and give you rights to manage it as you see fit
3. transfer the repo to you

We need a stable source of doctrine1 until we end support for our own Core-1.x version (which could frankly be years). Please do not interpret lack of immediate action as lack of support for your involvement and potential management/ownership. We just need to think things through carefully.

Finally, if this PR is agreed then we can merge it, but comments from @boutell have made me unsure of this so far :grinning:

**Comment by denis-sokolov** [comment]
@craigh, you do not see the `dev` branch because you recovered the source instead of forking the repository. We'll need to fix this. But nothing was lost.

As for @boutell's comments, I'm still unaware of any ability to add [custom keywords or functions in Doctrine 1](http://doctrine1.readthedocs.org/en/latest/en/manual/dql-doctrine-query-language.html).
There are also no tests for any of that and my PR did not break any tests.

**Comment by craigh** [comment]
@boutell - if you support the PR then I will merge it.

**Comment by boutell** [comment]
Looks like you can register custom functions but probably not custom
keywords. I withdraw my objection.

On Thu, Aug 20, 2015 at 8:53 AM, Craig Heydenburg notifications@github.com
wrote:

> @boutell https://github.com/boutell - if you support the PR then I will
> merge it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zikula/doctrine1/pull/1#issuecomment-132998084.

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Pull request merged**
